/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 1,000, find the sum of the even-valued terms.*/

var a = 1;
var b = 2;
var c = 0;

while(a < 1000){
  if(a % 2 === 0){
    sum += a;
  }
  c = a + b;
  a = b;
  b = c;
}

console.log(sum);

